package org.zalando.intellij.swagger.file;

public enum OpenApiFileType {

    UNDEFINED,
    MAIN,

    PARAMETERS,
    PARAMETERS_MULTIPLE_IN_ROOT,
    PARAMETERS_MULTIPLE_NOT_IN_ROOT,

    RESPONSES,
    RESPONSES_MULTIPLE_IN_ROOT,
    RESPONSES_MULTIPLE_NOT_IN_ROOT,

    EXAMPLES,
    EXAMPLES_MULTIPLE_IN_ROOT,
    EXAMPLES_MULTIPLE_NOT_IN_ROOT,

    REQUEST_BODIES,
    REQUEST_BODIES_MULTIPLE_IN_ROOT,
    REQUEST_BODIES_MULTIPLE_NOT_IN_ROOT,

    HEADERS,
    HEADERS_MULTIPLE_IN_ROOT,
    HEADERS_MULTIPLE_NOT_IN_ROOT,

    LINKS,
    LINKS_IN_ROOT,
    LINKS_NOT_IN_ROOT,

    CALLBACKS,
    CALLBACKS_IN_ROOT,
    CALLBACKS_NOT_IN_ROOT,

    SCHEMAS,
    SCHEMAS_IN_ROOT,
    SCHEMAS_NOT_IN_ROOT,

    SECURITY_SCHEMES,
    SECURITY_SCHEMES_IN_ROOT,
    SECURITY_SCHEMES_NOT_IN_ROOT,
}
