package org.zalando.intellij.swagger.file;

public enum OpenApiFileType {

    UNDEFINED,
    MAIN,

    SINGLE_PARAMETER,
    MULTIPLE_PARAMETERS,

    SINGLE_RESPONSE,
    MULTIPLE_RESPONSES,

    SINGLE_EXAMPLE,
    MULTIPLE_EXAMPLES,

    SINGLE_REQUEST_BODY,
    MULTIPLE_REQUEST_BODIES,

    SINGLE_HEADER,
    MULTIPLE_HEADERS,

    SINGLE_LINK,
    MULTIPLE_LINKS,

    SINGLE_CALLBACK,
    MULTIPLE_CALLBACKS,

    SINGLE_SCHEMA,
    MULTIPLE_SCHEMAS
}
