package org.zalando.intellij.swagger.file;

public enum SwaggerFileType {

    UNDEFINED,
    MAIN,
    DEFINITIONS,
    DEFINITIONS_MULTIPLE_IN_ROOT,
    DEFINITIONS_MULTIPLE_NOT_IN_ROOT,
    PARAMETERS,
    PARAMETERS_MULTIPLE_IN_ROOT,
    PARAMETERS_MULTIPLE_NOT_IN_ROOT
}
